/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Community;
import Model.CommunityDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.HospitalDirectory;
import Model.Hospital;
import Model.Patient;
import Model.PatientDirectory;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
//import medicalresourcemanagement.Patient;

/**
 *
 * @author Krishnakanth Naik Jarapala
 */
public class manageHousesjPanel extends javax.swing.JPanel {

    CommunityDirectory communitylist;
    PatientDirectory patientlists;
    private String checkError;
    /**
     * Creates new form AddHospital
     */
    public manageHousesjPanel(CommunityDirectory communitylist, PatientDirectory patientlist) {
        initComponents();
        this.communitylist = communitylist;
        this.patientlists = patientlist;
        btnUpdate.setEnabled(false);
        
        populateDataToTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbCommunity = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblCommVal = new javax.swing.JLabel();
        lblCityVal = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblHAval = new javax.swing.JLabel();
        txtHA = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblComm = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Community :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 100, -1));

        jLabel3.setText("City :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        cbCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCommunityActionPerformed(evt);
            }
        });
        cbCommunity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbCommunityKeyReleased(evt);
            }
        });
        add(cbCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 155, -1));

        btnView.setText("View & Update");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 530, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 51, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Manage Communities");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 29, 1068, -1));

        lblCommVal.setText(" ");
        add(lblCommVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 191, 30));

        lblCityVal.setText(" ");
        add(lblCityVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 191, 30));

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });
        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityKeyReleased(evt);
            }
        });
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 155, -1));

        jLabel4.setText("House Address:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        lblHAval.setText(" ");
        add(lblHAval, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 191, 30));

        txtHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAActionPerformed(evt);
            }
        });
        txtHA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHAKeyReleased(evt);
            }
        });
        add(txtHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 155, -1));

        tblComm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "House Address", "Community", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblComm);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 119, 1048, 139));
    }// </editor-fold>//GEN-END:initComponents

    private void cbCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCommunityActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblComm.getSelectedRow();  // gives index of selected rows
        if(selectedRowIndex < 0)
        {
           JOptionPane.showMessageDialog(this, "Select a entry to view");
           return;
        }
        
        txtHA.setText(patientlists.getPatientlist().get(selectedRowIndex).getHouseAddress());
        cbCommunity.setText(patientlists.getPatientlist().get(selectedRowIndex).getCommunityName());
        txtCity.setText(patientlists.getPatientlist().get(selectedRowIndex).getCityName());
        
        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        int selectedRowIndex = tblComm.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Record to update the details");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblComm.getModel();
        Patient selectedEntry = patientlists.getPatientlist().get(selectedRowIndex);

//        //Patient selectedEntry = (Patient) model.getValueAt(selectedRowIndex, 1);
////        selectedEntry.setEmployeeId(txtEmployeeId.getText());
//        selectedEntry.setName(txtname1.getText());
//        
//        selectedEntry.setAge(Integer.parseInt(txtage1.getText()));
//        selectedEntry.setPhone(Long.parseLong(txtphone1.getText()));
        selectedEntry.setHouseAddress(txtHA.getText());
        selectedEntry.setCommunityName(cbCommunity.getText());
        selectedEntry.setCityName(txtCity.getText());
        
        populateDataToTable();
        
        //once deleted all the fiels in view model will be deleted
        txtHA.setText("");
        cbCommunity.setText("");
        txtCity.setText("");
        btnUpdate.setEnabled(false);
           
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void cbCommunityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbCommunityKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(cbCommunity.getText());
        if(!patternmatch.matches())
        {
            lblCommVal.setText("Wrong Input, Please Try Again.");
        }
        else
        {
            lblCommVal.setText("");
        }
    }//GEN-LAST:event_cbCommunityKeyReleased

    private void txtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtCity.getText());
        if(!patternmatch.matches())
        {
            lblCityVal.setText("Wrong Input, Please Try Again.");
        }
        else
        {
            lblCityVal.setText("");
        }
    }//GEN-LAST:event_txtCityKeyReleased

    private void txtHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAActionPerformed

    private void txtHAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHAKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 \\d@$!-_ %*#?&'/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtHA.getText());
        if(!patternmatch.matches())
        {
            lblHAval.setText("Wrong Input, Please Try Again.");
        }
        else
        {
            lblHAval.setText("");
        }
    }//GEN-LAST:event_txtHAKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField cbCommunity;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCityVal;
    private javax.swing.JLabel lblCommVal;
    private javax.swing.JLabel lblHAval;
    private javax.swing.JTable tblComm;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtHA;
    // End of variables declaration//GEN-END:variables

 private void populateDataToTable() {
        //TableModel is used to manipulate table content.
        // type casts tablemodel to defaultTableModel.
    DefaultTableModel model = (DefaultTableModel) tblComm.getModel();
    model.setRowCount(0); // deleting empty records
    
    for (Patient patient : patientlists.getPatientlist()){

        Object[] row =  new Object[5];
        row[0] = patient.getPersonName();
        row[1] = patient.getPersonAge();
        row[2] = patient.getHouseAddress();
        row[3] = patient.getCommunityName();
        row[4] = patient.getCityName();

        model.addRow(row); // adds row to model

    }
}
}
