/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Doctor;
import Model.DoctorDirectory;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Krishnakanth Naik Jarapala
 */
public class manageDoctorjPanel extends javax.swing.JPanel {

    DoctorDirectory doctorlist;
    Doctor doctor;
    DoctorDirectory newdoctorlist;
    
    int error_flag = 0;
    /**
     * Creates new form manageDoctorjPanel
     * @param doctorlist
     */
    public manageDoctorjPanel(DoctorDirectory doctorlist) {
        initComponents();
        this.doctorlist = doctorlist;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTab_manage = new javax.swing.JTabbedPane();
        jtab_add = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblnameval = new javax.swing.JLabel();
        lblageval = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        lblage = new javax.swing.JLabel();
        lblHA = new javax.swing.JLabel();
        txtHA = new javax.swing.JTextField();
        lblHAval = new javax.swing.JLabel();
        lblcomm = new javax.swing.JLabel();
        txtcomm = new javax.swing.JTextField();
        lblcommval = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtcity = new javax.swing.JTextField();
        lblcityval = new javax.swing.JLabel();
        lblUN = new javax.swing.JLabel();
        txtun = new javax.swing.JTextField();
        lblunval = new javax.swing.JLabel();
        lblpwd = new javax.swing.JLabel();
        txtpwd = new javax.swing.JTextField();
        lblpwdval = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        txtSearchID = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        lbl_comm = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lbl_city = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_ha = new javax.swing.JTextField();
        txt_comm = new javax.swing.JTextField();
        txt_city = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        lbl_HA = new javax.swing.JLabel();
        lbl_un = new javax.swing.JLabel();
        lbl_pwd = new javax.swing.JLabel();
        txt_un = new javax.swing.JTextField();
        txt_pwd = new javax.swing.JTextField();
        lbl_gender = new javax.swing.JLabel();
        txt_gender = new javax.swing.JComboBox<>();
        txtSearchName = new javax.swing.JTextField();
        btn_searchID = new javax.swing.JButton();
        btn_searchName = new javax.swing.JButton();

        jTab_manage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTab_manageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTab_manageMouseEntered(evt);
            }
        });

        jtab_add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create New Doctor");
        jtab_add.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 1062, -1));

        lblName.setText("Name:");
        jtab_add.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 172, 88, 23));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });
        jtab_add.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 165, 238, -1));

        lblId.setText(" ");
        lblId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblIdKeyReleased(evt);
            }
        });
        jtab_add.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 26, 238, -1));

        lblnameval.setText(" ");
        jtab_add.add(lblnameval, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 169, 239, 22));

        lblageval.setText(" ");
        lblageval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblagevalKeyReleased(evt);
            }
        });
        jtab_add.add(lblageval, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 269, 239, 22));

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtageKeyReleased(evt);
            }
        });
        jtab_add.add(txtage, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 261, 238, -1));

        lblage.setText("Age:");
        jtab_add.add(lblage, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 261, 88, 30));

        lblHA.setText("House Address:");
        jtab_add.add(lblHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 312, 124, -1));

        txtHA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHAActionPerformed(evt);
            }
        });
        txtHA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHAKeyReleased(evt);
            }
        });
        jtab_add.add(txtHA, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 309, 238, -1));

        lblHAval.setText(" ");
        jtab_add.add(lblHAval, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 317, 438, 22));

        lblcomm.setText("Community:");
        jtab_add.add(lblcomm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, 30));

        txtcomm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcommActionPerformed(evt);
            }
        });
        txtcomm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcommKeyReleased(evt);
            }
        });
        jtab_add.add(txtcomm, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 358, 238, -1));

        lblcommval.setText(" ");
        jtab_add.add(lblcommval, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 366, 438, 22));

        lblCity.setText("City:");
        jtab_add.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 406, 88, 31));

        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });
        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcityKeyReleased(evt);
            }
        });
        jtab_add.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 407, 238, -1));

        lblcityval.setText(" ");
        jtab_add.add(lblcityval, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 415, 239, 22));

        lblUN.setText("User Name:");
        jtab_add.add(lblUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 456, 110, 30));

        txtun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunActionPerformed(evt);
            }
        });
        txtun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtunKeyReleased(evt);
            }
        });
        jtab_add.add(txtun, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 456, 238, -1));

        lblunval.setText(" ");
        jtab_add.add(lblunval, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 464, 239, 22));

        lblpwd.setText("Password:");
        jtab_add.add(lblpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 504, 88, 31));

        txtpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwdActionPerformed(evt);
            }
        });
        txtpwd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpwdKeyReleased(evt);
            }
        });
        jtab_add.add(txtpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 505, 238, -1));

        lblpwdval.setText(" ");
        jtab_add.add(lblpwdval, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 513, 239, 22));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jtab_add.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 595, 110, -1));

        lblgender.setText("Gender");
        jtab_add.add(lblgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 216, 75, -1));

        txtgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });
        jtab_add.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 213, 238, -1));

        jTab_manage.addTab("Add New Doctor", jtab_add);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Age", "Gender", "Community", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(displayTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 119, 1048, 139));

        txtSearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchIDActionPerformed(evt);
            }
        });
        txtSearchID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchIDKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 63, 176, -1));

        btnUpdate.setText("View & Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 276, 150, -1));

        btn_Save.setText("Save");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(519, 580, 110, -1));

        lbl_comm.setText("Community:");
        jPanel2.add(lbl_comm, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 463, 132, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 276, -1, -1));

        lbl_city.setText("City:");
        jPanel2.add(lbl_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 516, 111, -1));

        lbl_name.setText("Name:");
        jPanel2.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 316, 111, -1));

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 313, 219, -1));
        jPanel2.add(txt_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 361, 219, -1));

        txt_ha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_haActionPerformed(evt);
            }
        });
        jPanel2.add(txt_ha, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 409, 219, -1));
        jPanel2.add(txt_comm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 219, -1));
        jPanel2.add(txt_city, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 219, -1));

        jLabel2.setBackground(new java.awt.Color(255, 51, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Doctor Details");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 1062, -1));

        lbl_age.setText("Age:");
        jPanel2.add(lbl_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 364, 111, -1));

        lbl_HA.setText("House Address:");
        jPanel2.add(lbl_HA, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 412, 132, -1));

        lbl_un.setText("User Name:");
        jPanel2.add(lbl_un, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 455, 111, -1));

        lbl_pwd.setText("Password:");
        jPanel2.add(lbl_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 516, 111, -1));
        jPanel2.add(txt_un, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 460, 219, -1));
        jPanel2.add(txt_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 510, 219, -1));

        lbl_gender.setText("Gender:");
        jPanel2.add(lbl_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 414, 111, 20));

        txt_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        txt_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_genderActionPerformed(evt);
            }
        });
        jPanel2.add(txt_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 412, 219, -1));

        txtSearchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchNameActionPerformed(evt);
            }
        });
        txtSearchName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchNameKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(591, 63, 198, -1));

        btn_searchID.setText("Search by Doctor ID");
        btn_searchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchIDActionPerformed(evt);
            }
        });
        jPanel2.add(btn_searchID, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 63, -1, -1));

        btn_searchName.setText("Search by Doctor Name");
        btn_searchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchNameActionPerformed(evt);
            }
        });
        jPanel2.add(btn_searchName, new org.netbeans.lib.awtextra.AbsoluteConstraints(807, 63, -1, -1));

        jTab_manage.addTab("Manage Doctors", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTab_manage))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTab_manage)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void populateDataToTable() {
        //TableModel is used to manipulate table content.
        // type casts tablemodel to defaultTableModel.
    DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
   
    model.setRowCount(0); // used to delete empty records from table
    
    for (Doctor doctor : doctorlist.getDoctorlist()){
        
        Object[] row =  new Object[7];
        row[0] = doctor.getDoctorID(); 
        row[1] = doctor.getPersonName();
        row[2] = doctor.getPersonAge();
        row[3] = doctor.getPersonGender();
        row[4] = doctor.getHouseAddress();
        row[5] = doctor.getCommunityName();
        row[6] = doctor.getCityName();

        model.addRow(row); // adds row to model

    }
    }
    
    
    private void txtSearchIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchIDKeyReleased
        // TODO add your handling code here:
        
//        
//        if(!(txtSearchID.getText().isEmpty())) 
//        {
//            JOptionPane.showMessageDialog(this, "Select a record to view1111");
//            newdoctorlist.setNewdoctorlist(doctorlist.getDoctorlist());
//            newdoctorlist.SearchDoctorIdList(Integer.parseInt(txtSearchID.getText()));
//            populateDataToTable(newdoctorlist);
//            newdoctorlist.ClearTable();
//        }
//        else{
//            JOptionPane.showMessageDialog(this, "Select a record to view2222");
//        }
    }//GEN-LAST:event_txtSearchIDKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = displayTable.getSelectedRow();  // gives index of selected rows
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Select a record to view");
            btn_Save.setEnabled(false);
//            return;
        }
        else{
            btn_Save.setEnabled(true);
        }
        
        DefaultTableModel model = (DefaultTableModel)displayTable.getModel();
        
        //        Doctor selectedEntry = (Doctor) model.getValueAt(selectedRowIndex, 0);  // to get any value cells from table through row and column

        Doctor selectedEntry = doctorlist.getDoctorlist().get(selectedRowIndex);
        txt_name.setText(selectedEntry.getPersonName());
        txt_age.setText(String.valueOf(selectedEntry.getPersonAge()));
        txt_gender.setSelectedItem(selectedEntry.getPersonGender());
        txt_ha.setText(selectedEntry.getHouseAddress());
        txt_comm.setText(selectedEntry.getCommunityName());
        txt_city.setText(selectedEntry.getCityName());
        txt_un.setText(String.valueOf(selectedEntry.getUsername()));
        txt_pwd.setText(selectedEntry.getPassword());
       
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = displayTable.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Record to update the employee details");
//            btn_Save.setEnabled(false);
            return;
        }
        
        
        DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
        Doctor selectedEntry = doctorlist.getDoctorlist().get(selectedRowIndex);

//        Doctor selectedEntry = (Doctor) model.getValueAt(selectedRowIndex, 0);
//        System.out.println("name"+txtEmployeeName.getText());
        

        if(txt_name.getText().isEmpty() || txt_age.getText().isEmpty() || txt_ha.getText().isEmpty() || txt_comm.getText().isEmpty() || txt_city.getText().isEmpty() || txt_un.getText().isEmpty() || txt_pwd.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill Doctor Information Correctly");
        }
        else{           
            selectedEntry.setPersonName(txt_name.getText());
            selectedEntry.setPersonAge(Integer.parseInt(txt_age.getText()));
            selectedEntry.setPersonGender(txt_gender.getSelectedItem().toString());
            selectedEntry.setHouseAddress((txt_ha.getText()));
            selectedEntry.setCommunityName(txt_comm.getText());
            selectedEntry.setCityName(txt_city.getText());
            selectedEntry.setUsername(txt_un.getText());
            selectedEntry.setPassword(txt_pwd.getText());

            populateDataToTable();

            txt_name.setText("");
            txt_age.setText("");
            txt_gender.setSelectedIndex(-1);
            txt_ha.setText("");
            txt_comm.setText("");
            txt_city.setText("");
            txt_un.setText("");
            txt_pwd.setText("");
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = displayTable.getSelectedRow();  // gives index of selected rows
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Please select a Doctor profile");
            return;
           // int selectedRowIndex = displayTable.getSelectedRow();  // gives index of selected rows
        }
        DefaultTableModel model = (DefaultTableModel)displayTable.getModel();
        Doctor selectedEntry = doctorlist.getDoctorlist().get(selectedRowIndex);

//        Doctor selectedEntry = (Doctor) model.getValueAt(selectedRowIndex, 0);  // to get any value cells from table through row and column
        doctorlist.deleteProfile(selectedEntry);
        JOptionPane.showMessageDialog(this, "Selected Employee Deleted");
        populateDataToTable();
        
        txt_name.setText("");
        txt_age.setText("");
        txt_gender.setSelectedIndex(-1);
        txt_ha.setText("");
        txt_comm.setText("");
        txt_city.setText("");
        txt_un.setText("");
        txt_pwd.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_haActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_haActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_haActionPerformed

    private void txtHAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHAKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 \\d@$!-_ %*#?&'/:]+$";  
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtHA.getText());
        if(!patternmatch.matches())
        {
            lblHAval.setText("Wrong Input, Please Try Again.");
        }
        else
        {
            lblHAval.setText("");
        }
    }//GEN-LAST:event_txtHAKeyReleased

    private void txtHAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHAActionPerformed

    private void txtageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[0-9 +()-]{1,3}$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtage.getText());
        if(!patternmatch.matches())
        {
            lblageval.setText("Wrong Input, Please Enter Valid Age.");
            JOptionPane.showMessageDialog(this, "Please Enter Valid Age!");

            error_flag = 1;

        }
        else
        {
            lblageval.setText("");
            error_flag = 0;
        }
    }//GEN-LAST:event_txtageKeyReleased

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void lblIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIdKeyReleased

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtname.getText());
        if(!patternmatch.matches())
        {
            lblnameval.setText("Wrong Input, Please Enter Valid Name.");
        }
        else
        {
            lblnameval.setText("");
        }
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtcommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcommActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcommActionPerformed

    private void txtcommKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcommKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtcomm.getText());
        if(!patternmatch.matches())
        {
            lblcommval.setText("Wrong Input, Please Try Again.");
        }
        else
        {
            lblcommval.setText("");
        }
    }//GEN-LAST:event_txtcommKeyReleased

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtcityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtcity.getText());
        if(!patternmatch.matches())
        {
            lblcityval.setText("Wrong Input, Please Try Again.");
        }
        else
        {
            lblcityval.setText("");
        }
    }//GEN-LAST:event_txtcityKeyReleased

    private void txtunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunActionPerformed

    private void txtunKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtun.getText());
        if(!patternmatch.matches() )
        {
            lblunval.setText("Wrong Input, Please Try Again.");
            error_flag = 1;
        }
        else
        {
            lblunval.setText("");
            error_flag = 0;
        }

    }//GEN-LAST:event_txtunKeyReleased

    private void txtpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpwdActionPerformed

    private void txtpwdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpwdKeyReleased
        // TODO add your handling code here:
        String PatterN = "^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])[A-Za-z\\d@$!%*#?&]{8,}$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtpwd.getText());
        if(!patternmatch.matches())
        {
            lblpwdval.setText("Min 8 characters, atleast one letter, one number and one special character");
            error_flag =1;
        }
        else
        {
            lblpwdval.setText("");
            error_flag = 0;
        }
    }//GEN-LAST:event_txtpwdKeyReleased

    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:           
        String name = txtname.getText();
        String gender = txtgender.getSelectedItem().toString();
        int age = Integer.parseInt(txtage.getText());
        String houseaddress = txtHA.getText();
        String community = txtcomm.getText();
        String city = txtcity.getText();
        String username = txtun.getText();
        String pwd = txtpwd.getText();
        
        if(error_flag == 1 || lblnameval.getText() != "" || lblHAval.getText()!="" || lblcommval.getText() != "" || lblcityval.getText() != "" || lblunval.getText() != "" || lblpwdval.getText() != ""){
            JOptionPane.showMessageDialog(this, "Failed!, Please fill Doctor Information Correctly");
        }
        else{
            Doctor doc = doctorlist.addNewEmployee();
            doc.setPersonName(name);
            doc.setPersonGender(gender);
            doc.setPersonAge(age);
            doc.setHouseAddress(houseaddress);
            doc.setCommunityName(community);
            doc.setCityName(city);
            doc.setUsername(username);
            doc.setPassword(pwd);
            JOptionPane.showMessageDialog(this, "Doctor Information saved!");
            
            txtname.setText("");
            txtgender.setSelectedIndex(0);
            txtage.setText("");
            txtHA.setText("");
            txtcomm.setText("");
            txtcity.setText("");
            txtun.setText("");
            txtpwd.setText("");         
        }
        
          
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txt_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_genderActionPerformed

    private void jTab_manageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTab_manageMouseClicked
        // TODO add your handling code here:
        populateDataToTable();
    }//GEN-LAST:event_jTab_manageMouseClicked

    private void txtSearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchIDActionPerformed

    private void txtSearchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchNameActionPerformed

    private void txtSearchNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchNameKeyReleased

    private void lblagevalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblagevalKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblagevalKeyReleased

    private void btn_searchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchIDActionPerformed
        // TODO add your handling code here:
        if(!(txtSearchID.getText().isEmpty())) 
        {
            JOptionPane.showMessageDialog(this, "Clicked on Search and txt field is not empty");
//            newdoctorlist.SearchPersonIDList(Integer.parseInt(txtSearchID.getText()));
//            newEncounterPersonDirectory.AddAllNewPerson(newPersonDirectory.getPersonlist());
//            PopulateTable(newPersonDirectory.getNewpersonDirectory());
//            newPersonDirectory.ClearTable();
            
            
//            newdoctorlist.SearchDoctorIdList(Integer.parseInt(txtSearchID.getText()));
//            populateDataToTable(newdoctorlist);
//            newdoctorlist = newdoctorlist.SearchDoctorIdList(Integer.parseInt(txtSearchID.getText()))
//            populateDataToTable(newdoctorlist);
//            newdoctorlist.ClearTable();
        }
        else{
                JOptionPane.showMessageDialog(this, "Clicked on Search but txt field is empty");
            }
        
    }//GEN-LAST:event_btn_searchIDActionPerformed

    private void btn_searchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchNameActionPerformed

    private void jTab_manageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTab_manageMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTab_manageMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_searchID;
    private javax.swing.JButton btn_searchName;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTab_manage;
    private javax.swing.JPanel jtab_add;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblHA;
    private javax.swing.JLabel lblHAval;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblUN;
    private javax.swing.JLabel lbl_HA;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_comm;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_pwd;
    private javax.swing.JLabel lbl_un;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblageval;
    private javax.swing.JLabel lblcityval;
    private javax.swing.JLabel lblcomm;
    private javax.swing.JLabel lblcommval;
    private javax.swing.JLabel lblgender;
    private javax.swing.JLabel lblnameval;
    private javax.swing.JLabel lblpwd;
    private javax.swing.JLabel lblpwdval;
    private javax.swing.JLabel lblunval;
    private javax.swing.JTextField txtHA;
    private javax.swing.JTextField txtSearchID;
    private javax.swing.JTextField txtSearchName;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_city;
    private javax.swing.JTextField txt_comm;
    private javax.swing.JComboBox<String> txt_gender;
    private javax.swing.JTextField txt_ha;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_pwd;
    private javax.swing.JTextField txt_un;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcomm;
    private javax.swing.JComboBox<String> txtgender;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpwd;
    private javax.swing.JTextField txtun;
    // End of variables declaration//GEN-END:variables
}
