/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Doctor;
import Model.DoctorDirectory;
import Model.Encounter;
import Model.EncounterHistory;
import Model.Patient;
import Model.PatientDirectory;
import Model.Person;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.regex.Matcher;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Krishnakanth Naik Jarapala
 */
public class manageEncounterjPanel extends javax.swing.JPanel {

    /**
     * Creates new form manageEncounterjPanel
     */
    
    PatientDirectory patientlist;
    PatientDirectory newpatientlist;
    Patient patient;
    
    DoctorDirectory doctorlist;
    Doctor doctor;
    DoctorDirectory newdoctorlist;
    
    EncounterHistory encounterhistory;    
    ArrayList<Encounter> patientencounterhistory; 
    JPanel WorkArea;
    
    public manageEncounterjPanel( JPanel workarea, Patient patient, EncounterHistory encounterhistory, ArrayList<Encounter> patientencounterhistory)
    {
        initComponents();
        this.WorkArea = workarea;
        this.patient = patient;
        this.encounterhistory = encounterhistory;
        this.patientencounterhistory = patientencounterhistory;
//        
        txt1.setText(Integer.toString(patient.getPatientID()));
        txt2.setText(patient.getPersonName());
        txt3.setText(patient.getCommunityName());
        txt4.setText(patient.getCityName());
        
        txt1.setEnabled(false);
        txt2.setEnabled(false);
        txt3.setEnabled(false);
        txt4.setEnabled(false);
        
        PopulateTable1();
//        txt5.setText("");
//        txt6.setText("");
//        txt7.setText("");
//        txt8.setText("");
//        
//        if(toShow)
//        {
//             PopulateTable();
//        }
//        else
//        {
//            PopulateTable1();
//        }
    }
    
    public manageEncounterjPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        EncounterTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        lblval1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        lblval2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        lblval3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        lblval4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        lblval5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        lblval6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        lblval7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        txt8 = new javax.swing.JTextField();
        lblval8 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EncounterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Encounter ID", "Encounter Time", "Name", "Community", "Hospital ID", "Doctor ID", "Blood Pressure", "Temperature"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(EncounterTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 81, 1048, 139));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Patient Encounters");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 15, 1062, -1));

        lbl1.setText("Patient Id:");
        add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 266, 110, 30));

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt1KeyReleased(evt);
            }
        });
        add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 264, 238, -1));

        lblval1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        lblval1.setForeground(new java.awt.Color(255, 51, 51));
        lblval1.setText(" ");
        add(lblval1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 264, 438, 30));

        lbl2.setText("Patient Name:");
        add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 304, 110, 30));

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt2KeyReleased(evt);
            }
        });
        add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 302, 238, -1));

        lblval2.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        lblval2.setForeground(new java.awt.Color(255, 51, 51));
        lblval2.setText(" ");
        add(lblval2, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 302, 438, 30));

        lbl3.setText("Community:");
        add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 342, 110, 30));

        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt3KeyReleased(evt);
            }
        });
        add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 340, 238, -1));

        lblval3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        lblval3.setForeground(new java.awt.Color(255, 51, 51));
        lblval3.setText(" ");
        add(lblval3, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 340, 438, 30));

        lbl4.setText("City");
        add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 380, 110, 30));

        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });
        txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt4KeyReleased(evt);
            }
        });
        add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 378, 238, -1));

        lblval4.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        lblval4.setForeground(new java.awt.Color(255, 51, 51));
        lblval4.setText(" ");
        add(lblval4, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 378, 438, 30));

        lbl5.setText("Hospital ID:");
        add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 418, 110, 30));

        txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt5ActionPerformed(evt);
            }
        });
        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt5KeyReleased(evt);
            }
        });
        add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 416, 238, -1));

        lblval5.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        lblval5.setForeground(new java.awt.Color(255, 51, 51));
        lblval5.setText(" ");
        add(lblval5, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 416, 438, 30));

        lbl6.setText("Doctor ID:");
        add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 456, 110, 30));

        txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt6ActionPerformed(evt);
            }
        });
        txt6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt6KeyReleased(evt);
            }
        });
        add(txt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 454, 238, -1));

        lblval6.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        lblval6.setForeground(new java.awt.Color(255, 51, 51));
        lblval6.setText(" ");
        add(lblval6, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 454, 438, 30));

        lbl7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lbl7.setText("Blood Pressure:");
        add(lbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 494, 115, 30));

        txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt7ActionPerformed(evt);
            }
        });
        txt7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt7KeyReleased(evt);
            }
        });
        add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 492, 238, -1));

        lblval7.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        lblval7.setForeground(new java.awt.Color(255, 51, 51));
        lblval7.setText(" ");
        add(lblval7, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 492, 438, 30));

        lbl8.setText("Temperature:");
        add(lbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 532, 110, 30));

        txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt8ActionPerformed(evt);
            }
        });
        txt8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt8KeyReleased(evt);
            }
        });
        add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 530, 238, -1));

        lblval8.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        lblval8.setForeground(new java.awt.Color(255, 51, 51));
        lblval8.setText(" ");
        add(lblval8, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 530, 438, 30));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(466, 610, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyReleased
        // TODO add your handling code here:
//        String PatterN = "^[a-zA-Z0-9 '/:]+$";
//        Pattern pattern = Pattern.compile(PatterN);
//        Matcher patternmatch = pattern.matcher(txt1.getText());
//        if(!patternmatch.matches())
//        {
//            lblval1.setText("Wrong Input, Please Try Again.");
//        }
//        else
//        {
//            lblval1.setText("");
//        }
    }//GEN-LAST:event_txt1KeyReleased

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2KeyReleased

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void txt3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3KeyReleased

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void txt4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4KeyReleased

    private void txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt5ActionPerformed

    private void txt5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt5KeyReleased

    private void txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6ActionPerformed

    private void txt6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt6KeyReleased

    private void txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt7ActionPerformed

    private void txt7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt7KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt7KeyReleased

    private void txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8ActionPerformed

    private void txt8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt8KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt8KeyReleased

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        Encounter encounter = encounterhistory.AddNewEncounter();
        
        if(lblval8.getText().equals(" ") && lblval7.getText().equals(" ") && lblval6.getText().equals(" ") && lblval5.getText().equals(" "))
        {   
                  
            encounter.setPatientID(patient.getPatientID());
            encounter.setPatient_name(patient.getPersonName());
            encounter.setCity(patient.getCityName());
            encounter.setCommunity(patient.getCommunityName());
            encounter.setHospital_id(Integer.parseInt(txt5.getText()));
            encounter.setEncounter_time(LocalDateTime.now());
            encounter.setDoctor_id(Integer.parseInt(txt6.getText()));
            encounter.setBloodPressure(Double.parseDouble(txt7.getText()));
            encounter.setTemperature(Double.parseDouble(txt8.getText()));

            PopulateTable1();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Enter Correct Data and try again");
            return;
        }

        txt5.setText("");
        txt6.setText("");
        txt7.setText("");
        txt8.setText("");
    }//GEN-LAST:event_btnAddActionPerformed
    
    private void PopulateTable() {

        DefaultTableModel model = (DefaultTableModel) EncounterTable.getModel();
        
        model.setRowCount(0);
        
        for(Encounter encounter : encounterhistory.getEncounterHistory())
        {
            Object[] row = new Object[6];
            row[0] = encounter.getEncounter_id();
            row[1] = encounter.getEncounter_time();
            row[2] = encounter.getPatientID();
            row[3] = encounter.getPatient_name();
            row[4] = encounter.getBloodPressure();
            row[5] = encounter.getTemperature();
//            row[6] = encounter.getCommunity();
//            row[7] = encounter.getHouseAddress();
//            row[8] = encounter.getMinimumReading();
//            row[9] = encounter.getBloodPressure();
//            row[10] = encounter.getTemperature();
            
            model.addRow(row);
        }
    }
    
     private void PopulateTable1() {

        DefaultTableModel model = (DefaultTableModel) EncounterTable.getModel();
        
        model.setRowCount(0);
        
        for(Encounter encounter : encounterhistory.getEncounterHistory())
        {
            Object[] row = new Object[6];
            row[0] = encounter.getEncounter_id();
            row[1] = encounter.getEncounter_time();
            row[2] = encounter.getPatientID();
            row[3] = encounter.getPatient_name();
            row[4] = encounter.getBloodPressure();
            row[5] = encounter.getTemperature();
//            row[6] = encounter.getCommunity();
//            row[7] = encounter.getHouseAddress();
//            row[8] = encounter.getMinimumReading();
//            row[9] = encounter.getBloodPressure();
//            row[10] = encounter.getTemperature();
            
            if(encounter.getPatientID() == Integer.parseInt(txt1.getText()))
            {
                model.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EncounterTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JLabel lblval1;
    private javax.swing.JLabel lblval2;
    private javax.swing.JLabel lblval3;
    private javax.swing.JLabel lblval4;
    private javax.swing.JLabel lblval5;
    private javax.swing.JLabel lblval6;
    private javax.swing.JLabel lblval7;
    private javax.swing.JLabel lblval8;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    // End of variables declaration//GEN-END:variables
}
