/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Doctor;
import Model.DoctorDirectory;
import Model.Patient;
import Model.PatientDirectory;
import java.awt.CardLayout;

/**
 *
 * @author Krishnakanth Naik Jarapala
 */
public class SystemAdmin extends javax.swing.JFrame {
    
    PatientDirectory patientlist;
    Patient patient;
    DoctorDirectory doctorlist;
    Doctor doctor;
    /**
     * Creates new form SystemAdmin
     */
    public SystemAdmin() {
        initComponents();
        patientlist = new PatientDirectory();
        patient = new Patient();
        doctorlist = new DoctorDirectory();
        doctor = new Doctor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        patientbtn = new javax.swing.JButton();
        doctorbtn = new javax.swing.JButton();
        hospitalbtn = new javax.swing.JButton();
        encounterbtn = new javax.swing.JButton();
        WorkArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        controlPanel.setBackground(new java.awt.Color(255, 153, 153));
        controlPanel.setForeground(new java.awt.Color(102, 102, 0));
        controlPanel.setPreferredSize(new java.awt.Dimension(200, 700));

        patientbtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        patientbtn.setText("Manage Patient");
        patientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientbtnActionPerformed(evt);
            }
        });

        doctorbtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        doctorbtn.setText("Manage Doctor");
        doctorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorbtnActionPerformed(evt);
            }
        });

        hospitalbtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        hospitalbtn.setText("Manage Hospitals");
        hospitalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalbtnActionPerformed(evt);
            }
        });

        encounterbtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        encounterbtn.setText("Manage Encounters");
        encounterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patientbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(doctorbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(encounterbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hospitalbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(patientbtn)
                .addGap(30, 30, 30)
                .addComponent(doctorbtn)
                .addGap(26, 26, 26)
                .addComponent(encounterbtn)
                .addGap(28, 28, 28)
                .addComponent(hospitalbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(293, 293, 293))
        );

        SplitPane.setLeftComponent(controlPanel);

        WorkArea.setBackground(new java.awt.Color(255, 204, 204));
        WorkArea.setPreferredSize(new java.awt.Dimension(1100, 700));
        WorkArea.setLayout(new java.awt.CardLayout());
        SplitPane.setRightComponent(WorkArea);

        getContentPane().add(SplitPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalbtnActionPerformed

    private void patientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientbtnActionPerformed
        // TODO add your handling code here:
        managePatientJPanel mp = new managePatientJPanel(patientlist);
        WorkArea.add("managePatientJPanel", mp);
        CardLayout cardlayout = (CardLayout) WorkArea.getLayout();
        cardlayout.next(WorkArea);
//        SplitPane.setRightComponent(mp);
    }//GEN-LAST:event_patientbtnActionPerformed

    private void doctorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorbtnActionPerformed
        // TODO add your handling code here:
        manageDoctorjPanel mp = new manageDoctorjPanel(doctorlist);
        WorkArea.add("manageDoctorjPanel", mp);
        CardLayout cardlayout = (CardLayout) WorkArea.getLayout();
        cardlayout.next(WorkArea);
        
    }//GEN-LAST:event_doctorbtnActionPerformed

    private void encounterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encounterbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JPanel WorkArea;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JButton doctorbtn;
    private javax.swing.JButton encounterbtn;
    private javax.swing.JButton hospitalbtn;
    private javax.swing.JButton patientbtn;
    // End of variables declaration//GEN-END:variables
}
