/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import java.awt.Image;
import java.awt.List;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.regex.*;

import Model.EmployeeInformation;
import Model.EmployeeInformationHistory;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author jkkn7
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanlel
     */
    
    EmployeeInformationHistory history;
    public String photoPath;
    public String gender;
    public Date startDate;
    
    
    
    public CreateJPanel(EmployeeInformationHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        txtEmployeeId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblEmployeeAge = new javax.swing.JLabel();
        txtEmployeeAge = new javax.swing.JTextField();
        lblEmployeeGender = new javax.swing.JLabel();
        r_btnMale = new javax.swing.JRadioButton();
        r_btnFemale = new javax.swing.JRadioButton();
        lblEmployeePhnNumber = new javax.swing.JLabel();
        txtEmployeePhnNumber = new javax.swing.JTextField();
        lblEmployeeEmail = new javax.swing.JLabel();
        txtEmployeeEmail = new javax.swing.JTextField();
        lblEmployeeStartDate = new javax.swing.JLabel();
        txtEmployeeLevel = new javax.swing.JTextField();
        lblEmployeeLevel = new javax.swing.JLabel();
        lblEmployeePostitionTitle = new javax.swing.JLabel();
        lblEmployeeTeamInfo = new javax.swing.JLabel();
        txtEmployeeTeamInfo = new javax.swing.JTextField();
        txtEmployeePositionTitle = new javax.swing.JTextField();
        jButtonPhotoUpload = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblTI = new javax.swing.JLabel();
        lblPT = new javax.swing.JLabel();
        lblEmployeePhoto = new javax.swing.JLabel();
        jcalStartDate = new com.toedter.calendar.JDateChooser();
        jLabel_Photo = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create New Employee Data");

        lblEmployeeName.setText("Name:");

        lblEmployeeID.setText("Employee ID:");

        txtEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeNameActionPerformed(evt);
            }
        });
        txtEmployeeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeNameKeyReleased(evt);
            }
        });

        txtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIdActionPerformed(evt);
            }
        });
        txtEmployeeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeIdKeyReleased(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblEmployeeAge.setText("Age:");

        txtEmployeeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeAgeActionPerformed(evt);
            }
        });
        txtEmployeeAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeAgeKeyReleased(evt);
            }
        });

        lblEmployeeGender.setText("Gender:");

        r_btnMale.setText("Male");
        r_btnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btnMaleActionPerformed(evt);
            }
        });

        r_btnFemale.setText("Female");
        r_btnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btnFemaleActionPerformed(evt);
            }
        });

        lblEmployeePhnNumber.setText("Contact:");

        txtEmployeePhnNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeePhnNumberActionPerformed(evt);
            }
        });
        txtEmployeePhnNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeePhnNumberKeyReleased(evt);
            }
        });

        lblEmployeeEmail.setText("Email:");

        txtEmployeeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeEmailActionPerformed(evt);
            }
        });
        txtEmployeeEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeEmailKeyReleased(evt);
            }
        });

        lblEmployeeStartDate.setText("Start Date:");

        txtEmployeeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeLevelActionPerformed(evt);
            }
        });
        txtEmployeeLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeLevelKeyReleased(evt);
            }
        });

        lblEmployeeLevel.setText("Level:");

        lblEmployeePostitionTitle.setText("Position Title:");

        lblEmployeeTeamInfo.setText("Team Information:");

        txtEmployeeTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeTeamInfoActionPerformed(evt);
            }
        });
        txtEmployeeTeamInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeTeamInfoKeyReleased(evt);
            }
        });

        txtEmployeePositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeePositionTitleActionPerformed(evt);
            }
        });
        txtEmployeePositionTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeePositionTitleKeyReleased(evt);
            }
        });

        jButtonPhotoUpload.setText("Upload");
        jButtonPhotoUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhotoUploadActionPerformed(evt);
            }
        });

        lblId.setText(" ");
        lblId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblIdKeyReleased(evt);
            }
        });

        lblName.setText(" ");

        lblAge.setText(" ");

        lblContact.setText(" ");

        lblEmail.setText(" ");

        lblStartDate.setText(" ");

        lblLevel.setText(" ");

        lblTI.setText(" ");

        lblPT.setText(" ");

        lblEmployeePhoto.setText(" ");

        jLabel_Photo.setText("Photo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEmployeeStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(302, 302, 302))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcalStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEmployeePostitionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmployeeLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmployeeTeamInfo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmployeeTeamInfo)
                            .addComponent(lblLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEmployeeLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(txtEmployeePositionTitle))
                        .addGap(96, 96, 96))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmployeeName)
                                        .addComponent(lblEmployeeAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblEmployeeID))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmployeeId, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(lblId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmployeeName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(r_btnMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(r_btnFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEmployeeAge)
                                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAge, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(lblEmployeePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addComponent(jButtonPhotoUpload))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(177, 177, 177)
                                        .addComponent(jLabel_Photo))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEmployeePhnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmployeePhnNumber)
                                    .addComponent(lblContact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblEmployeeID, lblEmployeeName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcalStartDate, txtEmployeeAge, txtEmployeeEmail, txtEmployeeId, txtEmployeeLevel, txtEmployeeName, txtEmployeePhnNumber, txtEmployeePositionTitle, txtEmployeeTeamInfo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeID)
                            .addComponent(txtEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeName)
                            .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblEmployeeAge))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmployeeAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(r_btnMale, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(r_btnFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblEmployeeGender, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel_Photo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmployeePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPhotoUpload)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeePhnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeePhnNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblContact)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmployeeStartDate)
                            .addComponent(jcalStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lblStartDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmployeeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmployeeLevel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLevel)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeeTeamInfo)
                            .addComponent(txtEmployeeTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmployeePostitionTitle)
                            .addComponent(txtEmployeePositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPT)))
                .addGap(21, 21, 21)
                .addComponent(btnSave)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblEmployeeID, lblEmployeeName});

    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeNameActionPerformed

    private void txtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat f = new SimpleDateFormat();
        
//        f.parse(f.format(jcalStartDate.getDate()))
        
        int employeeId = Integer.parseInt(txtEmployeeId.getText());
        String employeeName = txtEmployeeName.getText();
        int employeeAge = Integer.parseInt(txtEmployeeAge.getText());
        String employeeGender = gender;
        double employeePhnNumber = Double.parseDouble(txtEmployeePhnNumber.getText());
        String employeeEmail = txtEmployeeEmail.getText();
//        Date employeeStartDate = txtEmployeeStartDate.getDate();
//        Date employeeStartDate = f.parse(f.format(jcalStartDate.getDate()));
        Date employeeStartDate = jcalStartDate.getDate();

        String employeeLevel = txtEmployeeLevel.getText();
        String employeeTeamInfo = txtEmployeeTeamInfo.getText();
        String employeePositionTitle = txtEmployeePositionTitle.getText();
        String employeePhoto = photoPath;
        
//        Append to ArrayList of employees
        EmployeeInformation ei = history.addNewEmployee();
        ei.setEmployeeId(employeeId);
        ei.setEmployeeName(employeeName);
        ei.setEmployeeAge(employeeAge);
        ei.setEmployeePhnNumber(employeePhnNumber);
        ei.setEmployeeEmail(employeeEmail);
        ei.setEmployeeStartDate(employeeStartDate);
        ei.setEmployeeLevel(employeeLevel);
        ei.setEmployeeTeamInfo(employeeTeamInfo);
        ei.setEmployeePositionTitle(employeePositionTitle);
        ei.setEmployeePhoto(employeePhoto);
        
        
        JOptionPane.showMessageDialog(this, "Employee Information saved!");
        
        txtEmployeeId.setText("");
        txtEmployeeName.setText("");
        txtEmployeeAge.setText("");
//        gender = null;
        r_btnMale.setSelected(false);
        r_btnFemale.setSelected(false);
        txtEmployeePhnNumber.setText("");
        txtEmployeeEmail.setText("");
        jcalStartDate.setDate(null);
        txtEmployeeLevel.setText("");
        txtEmployeeTeamInfo.setText("");
        txtEmployeePositionTitle.setText("");
        lblEmployeePhoto.setIcon(null);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtEmployeeNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeNameKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeName.getText());
        if(!patternmatch.matches())
        {
            lblName.setText("Wrong Input, Please Enter Valid Input.");
        }
        else
        {
            lblName.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeNameKeyReleased

    private void txtEmployeeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeAgeActionPerformed

    private void txtEmployeeAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeAgeKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[0-9 +()-]{1,3}$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeAge.getText());
        if(!patternmatch.matches())
        {
            lblAge.setText("Wrong Input, Please Enter Valid Input.");
        }
        else
        {
            lblAge.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeAgeKeyReleased

    private void r_btnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btnFemaleActionPerformed
        // TODO add your handling code here:
        if(r_btnFemale.isSelected())
        {
        gender ="Female";
        r_btnFemale.setSelected(true);
        r_btnMale.setSelected(false);
        }
    }//GEN-LAST:event_r_btnFemaleActionPerformed

    private void txtEmployeePhnNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeePhnNumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmployeePhnNumberActionPerformed

    private void txtEmployeePhnNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeePhnNumberKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[0-9 +()-]{10}$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeePhnNumber.getText());
        if(!patternmatch.matches())
        {
            lblContact.setText("Wrong Input, Please Enter 10 digits.");
        }
        else
        {
            lblContact.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeePhnNumberKeyReleased

    private void txtEmployeeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeEmailActionPerformed

    private void txtEmployeeEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeEmailKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9+_.-]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeEmail.getText());
        if(!patternmatch.matches())
        {
            lblEmail.setText("Wrong Input,Please Enter Valid Input.");
        }
        else
        {
            lblEmail.setText(" "); 
        }

    }//GEN-LAST:event_txtEmployeeEmailKeyReleased

    private void txtEmployeeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeLevelActionPerformed

    private void txtEmployeeLevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeLevelKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeLevel.getText());
        if(!patternmatch.matches())
        {
            lblLevel.setText("Wrong Input. Please Try Again.");
        }
        else
        {
            lblLevel.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeLevelKeyReleased

    private void txtEmployeeTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeTeamInfoActionPerformed

    private void txtEmployeeTeamInfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeTeamInfoKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeTeamInfo.getText());
        if(!patternmatch.matches())
        {
            lblTI.setText("Wrong Input. Please Try Again.");
        }
        else
        {
            lblTI.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeTeamInfoKeyReleased

    private void txtEmployeePositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeePositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeePositionTitleActionPerformed

    private void txtEmployeePositionTitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeePositionTitleKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeePositionTitle.getText());
        if(!patternmatch.matches())
        {
            lblPT.setText("Wrong Input. Please Try Again.");
        }
        else
        {
            lblPT.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeePositionTitleKeyReleased

    private void r_btnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btnMaleActionPerformed
        // TODO add your handling code here:
        if(r_btnMale.isSelected())
        {
        gender ="Male";
        r_btnMale.setSelected(true);
        r_btnFemale.setSelected(false);
        }
        
    }//GEN-LAST:event_r_btnMaleActionPerformed

    private void txtEmployeeIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeIdKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[0-9]{1,30}$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeId.getText());
        if(!patternmatch.matches())
        {
            lblId.setText("Wrong Input, Please Enter Integer.");
        }
        else
        {
            lblId.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeIdKeyReleased

    private void lblIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIdKeyReleased

    private void jButtonPhotoUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhotoUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
         
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION)
        {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            photoPath = selectedImagePath;
//            history.setPhoto(selectedImagePath);
            
            ImageIcon ii = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lblEmployeePhoto.getWidth(), lblEmployeePhoto.getHeight(), Image.SCALE_SMOOTH);
            lblEmployeePhoto.setIcon(new ImageIcon(image));
        }                   
    }//GEN-LAST:event_jButtonPhotoUploadActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButtonPhotoUpload;
    private javax.swing.JLabel jLabel_Photo;
    private com.toedter.calendar.JDateChooser jcalStartDate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeeAge;
    private javax.swing.JLabel lblEmployeeEmail;
    private javax.swing.JLabel lblEmployeeGender;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeLevel;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblEmployeePhnNumber;
    private javax.swing.JLabel lblEmployeePhoto;
    private javax.swing.JLabel lblEmployeePostitionTitle;
    private javax.swing.JLabel lblEmployeeStartDate;
    private javax.swing.JLabel lblEmployeeTeamInfo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPT;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTI;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton r_btnFemale;
    private javax.swing.JRadioButton r_btnMale;
    private javax.swing.JTextField txtEmployeeAge;
    private javax.swing.JTextField txtEmployeeEmail;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtEmployeeLevel;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEmployeePhnNumber;
    private javax.swing.JTextField txtEmployeePositionTitle;
    private javax.swing.JTextField txtEmployeeTeamInfo;
    // End of variables declaration//GEN-END:variables


    

}
