/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package employeedirectoryui;

import java.awt.Image;
import java.awt.List;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.regex.*;

import employeedirectorymodel.EmployeeInformation;
import employeedirectorymodel.EmployeeInformationHistory;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Krishna Kanth J
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanlel
     */
    
    EmployeeInformationHistory history;
    public String photoPath;
    public String gender;
    public Date startDate;
    public int error_flag = 0;
    
    
    
    public CreateJPanel(EmployeeInformationHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        txtEmployeeId = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblEmployeeAge = new javax.swing.JLabel();
        txtEmployeeAge = new javax.swing.JTextField();
        lblEmployeeGender = new javax.swing.JLabel();
        r_btnMale = new javax.swing.JRadioButton();
        r_btnFemale = new javax.swing.JRadioButton();
        lblEmployeePhnNumber = new javax.swing.JLabel();
        txtEmployeePhnNumber = new javax.swing.JTextField();
        lblEmployeeEmail = new javax.swing.JLabel();
        txtEmployeeEmail = new javax.swing.JTextField();
        lblEmployeeStartDate = new javax.swing.JLabel();
        txtEmployeeLevel = new javax.swing.JTextField();
        lblEmployeeLevel = new javax.swing.JLabel();
        lblEmployeePostitionTitle = new javax.swing.JLabel();
        lblEmployeeTeamInfo = new javax.swing.JLabel();
        txtEmployeeTeamInfo = new javax.swing.JTextField();
        txtEmployeePositionTitle = new javax.swing.JTextField();
        jButtonPhotoUpload = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblTI = new javax.swing.JLabel();
        lblPT = new javax.swing.JLabel();
        lblEmployeePhoto = new javax.swing.JLabel();
        jcalStartDate = new com.toedter.calendar.JDateChooser();
        jLabel_Photo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create New Employee Data");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 17, 870, 55));

        lblEmployeeName.setText("Name:");
        add(lblEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 178, 89, -1));

        lblEmployeeID.setText("Employee ID:");
        add(lblEmployeeID, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 118, -1, -1));

        txtEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeNameActionPerformed(evt);
            }
        });
        txtEmployeeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeNameKeyReleased(evt);
            }
        });
        add(txtEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 175, 238, -1));

        txtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIdActionPerformed(evt);
            }
        });
        txtEmployeeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeIdKeyReleased(evt);
            }
        });
        add(txtEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 115, 238, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 552, 79, -1));

        lblEmployeeAge.setText("Age:");
        add(lblEmployeeAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 234, 88, -1));

        txtEmployeeAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeAgeActionPerformed(evt);
            }
        });
        txtEmployeeAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeAgeKeyReleased(evt);
            }
        });
        add(txtEmployeeAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 235, 238, -1));

        lblEmployeeGender.setText("Gender:");
        add(lblEmployeeGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 295, 88, 29));

        r_btnMale.setText("Male");
        r_btnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btnMaleActionPerformed(evt);
            }
        });
        add(r_btnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 302, -1, 22));

        r_btnFemale.setText("Female");
        r_btnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_btnFemaleActionPerformed(evt);
            }
        });
        add(r_btnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 302, 90, 22));

        lblEmployeePhnNumber.setText("Contact:");
        add(lblEmployeePhnNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 356, 88, -1));

        txtEmployeePhnNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeePhnNumberActionPerformed(evt);
            }
        });
        txtEmployeePhnNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeePhnNumberKeyReleased(evt);
            }
        });
        add(txtEmployeePhnNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 353, 238, -1));

        lblEmployeeEmail.setText("Email:");
        add(lblEmployeeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 416, 88, -1));

        txtEmployeeEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeEmailActionPerformed(evt);
            }
        });
        txtEmployeeEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeEmailKeyReleased(evt);
            }
        });
        add(txtEmployeeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 413, 238, -1));

        lblEmployeeStartDate.setText("Start Date:");
        add(lblEmployeeStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 479, 122, -1));

        txtEmployeeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeLevelActionPerformed(evt);
            }
        });
        txtEmployeeLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeLevelKeyReleased(evt);
            }
        });
        add(txtEmployeeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 353, 238, -1));

        lblEmployeeLevel.setText("Level:");
        add(lblEmployeeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 356, 124, -1));

        lblEmployeePostitionTitle.setText("Position Title:");
        add(lblEmployeePostitionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 480, 124, -1));

        lblEmployeeTeamInfo.setText("Team Information:");
        add(lblEmployeeTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 420, -1, -1));

        txtEmployeeTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeTeamInfoActionPerformed(evt);
            }
        });
        txtEmployeeTeamInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeTeamInfoKeyReleased(evt);
            }
        });
        add(txtEmployeeTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 417, 238, -1));

        txtEmployeePositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeePositionTitleActionPerformed(evt);
            }
        });
        txtEmployeePositionTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeePositionTitleKeyReleased(evt);
            }
        });
        add(txtEmployeePositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 477, 238, -1));

        jButtonPhotoUpload.setText("Upload");
        jButtonPhotoUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhotoUploadActionPerformed(evt);
            }
        });
        add(jButtonPhotoUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 298, -1, -1));

        lblId.setText(" ");
        lblId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblIdKeyReleased(evt);
            }
        });
        add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 148, 238, -1));

        lblName.setText(" ");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 208, 238, -1));

        lblAge.setText(" ");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 268, 221, -1));

        lblContact.setText(" ");
        add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 386, 238, -1));

        lblEmail.setText(" ");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 446, 238, -1));

        lblStartDate.setText(" ");
        add(lblStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 505, 0, -1));

        lblLevel.setText(" ");
        add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 386, 238, -1));

        lblTI.setText(" ");
        add(lblTI, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 450, 238, -1));

        lblPT.setText(" ");
        add(lblPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 510, 238, -1));

        lblEmployeePhoto.setText(" ");
        add(lblEmployeePhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(536, 139, 165, 153));
        add(jcalStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 473, 238, -1));

        jLabel_Photo.setText("Photo");
        add(jLabel_Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 106, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeNameActionPerformed

    private void txtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat f = new SimpleDateFormat();
        
//        f.parse(f.format(jcalStartDate.getDate()))
        
        String employeeId = txtEmployeeId.getText();
        String employeeName = txtEmployeeName.getText();
        int employeeAge = Integer.parseInt(txtEmployeeAge.getText());
        String employeeGender = gender;
        long employeePhnNumber = Long.parseLong(txtEmployeePhnNumber.getText());
        String employeeEmail = txtEmployeeEmail.getText();
//        Date employeeStartDate = txtEmployeeStartDate.getDate();
//        Date employeeStartDate = f.parse(f.format(jcalStartDate.getDate()));
        Date employeeStartDate = jcalStartDate.getDate();

        String employeeLevel = txtEmployeeLevel.getText();
        String employeeTeamInfo = txtEmployeeTeamInfo.getText();
        String employeePositionTitle = txtEmployeePositionTitle.getText();
        String employeePhoto = photoPath;
        
        if(lblId.getText() == " " && lblName.getText() == " " && lblAge.getText() == " " && lblContact.getText() == " " && lblEmail.getText() == " " && lblLevel.getText() == " " && lblTI.getText() == " " && lblPT.getText() == " ")
        {
            //      Append to ArrayList of employees
            EmployeeInformation ei = history.addNewEmployee();
            ei.setEmployeeId(employeeId);
            ei.setEmployeeName(employeeName);
            ei.setEmployeeAge(employeeAge);
            ei.setEmployeeGender(employeeGender);
            ei.setEmployeePhnNumber(employeePhnNumber);
            ei.setEmployeeEmail(employeeEmail);
            ei.setEmployeeStartDate(employeeStartDate);
            ei.setEmployeeLevel(employeeLevel);
            ei.setEmployeeTeamInfo(employeeTeamInfo);
            ei.setEmployeePositionTitle(employeePositionTitle);
            ei.setEmployeePhoto(employeePhoto);

            JOptionPane.showMessageDialog(this, "Employee Information saved!");
        }
        else{
            JOptionPane.showMessageDialog(this, "Failed!, Please fill Employee Information Correctly");
        }

        
        txtEmployeeId.setText("");
        txtEmployeeName.setText("");
        txtEmployeeAge.setText("");
        gender = null;
        r_btnMale.setSelected(false);
        r_btnFemale.setSelected(false);
        txtEmployeePhnNumber.setText("");
        txtEmployeeEmail.setText("");
        jcalStartDate.setDate(null);
        txtEmployeeLevel.setText("");
        txtEmployeeTeamInfo.setText("");
        txtEmployeePositionTitle.setText("");
        lblEmployeePhoto.setIcon(null);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtEmployeeNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeNameKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeName.getText());
        if(!patternmatch.matches())
        {
            lblName.setText("Wrong Input, Please Enter Valid Input.");
        }
        else
        {
            lblName.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeNameKeyReleased

    private void txtEmployeeAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeAgeActionPerformed

    private void txtEmployeeAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeAgeKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[0-9 +()-]{1,3}$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeAge.getText());
        if(!patternmatch.matches())
        {
            lblAge.setText("Wrong Input, Please Enter Valid Input.");
        }
        else
        {
            lblAge.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeAgeKeyReleased

    private void r_btnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btnFemaleActionPerformed
        // TODO add your handling code here:
        if(r_btnFemale.isSelected())
        {
        gender ="Female";
        r_btnFemale.setSelected(true);
        r_btnMale.setSelected(false);
        }
    }//GEN-LAST:event_r_btnFemaleActionPerformed

    private void txtEmployeePhnNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeePhnNumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtEmployeePhnNumberActionPerformed

    private void txtEmployeePhnNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeePhnNumberKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[0-9 +()-]{10}$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeePhnNumber.getText());
        if(!patternmatch.matches())
        {
            lblContact.setText("Wrong Input, Please Enter 10 digits.");
        }
        else
        {
            lblContact.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeePhnNumberKeyReleased

    private void txtEmployeeEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeEmailActionPerformed

    private void txtEmployeeEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeEmailKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9+_.-]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeEmail.getText());
        if(!patternmatch.matches())
        {
            lblEmail.setText("Wrong Input,Please Enter Valid Input.");
        }
        else
        {
            lblEmail.setText(" "); 
        }

    }//GEN-LAST:event_txtEmployeeEmailKeyReleased

    private void txtEmployeeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeLevelActionPerformed

    private void txtEmployeeLevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeLevelKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeLevel.getText());
        if(!patternmatch.matches())
        {
            lblLevel.setText("Wrong Input. Please Try Again.");
        }
        else
        {
            lblLevel.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeLevelKeyReleased

    private void txtEmployeeTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeTeamInfoActionPerformed

    private void txtEmployeeTeamInfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeTeamInfoKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeTeamInfo.getText());
        if(!patternmatch.matches())
        {
            lblTI.setText("Wrong Input. Please Try Again.");
        }
        else
        {
            lblTI.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeTeamInfoKeyReleased

    private void txtEmployeePositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeePositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeePositionTitleActionPerformed

    private void txtEmployeePositionTitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeePositionTitleKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeePositionTitle.getText());
        if(!patternmatch.matches())
        {
            lblPT.setText("Wrong Input. Please Try Again.");
        }
        else
        {
            lblPT.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeePositionTitleKeyReleased

    private void r_btnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_btnMaleActionPerformed
        // TODO add your handling code here:
        if(r_btnMale.isSelected())
        {
        gender ="Male";
        r_btnMale.setSelected(true);
        r_btnFemale.setSelected(false);
        }
        
    }//GEN-LAST:event_r_btnMaleActionPerformed

    private void txtEmployeeIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeIdKeyReleased
        // TODO add your handling code here:
        String PatterN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PatterN);
        Matcher patternmatch = pattern.matcher(txtEmployeeId.getText());
        if(!patternmatch.matches())
        {
            lblId.setText("Wrong Input, Please Enter Integer.");
        }
        else
        {
            lblId.setText(" ");
        }
    }//GEN-LAST:event_txtEmployeeIdKeyReleased

    private void lblIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIdKeyReleased

    private void jButtonPhotoUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhotoUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
         
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION)
        {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            photoPath = selectedImagePath;
//            history.setPhoto(selectedImagePath);
            
            ImageIcon ii = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lblEmployeePhoto.getWidth(), lblEmployeePhoto.getHeight(), Image.SCALE_SMOOTH);
            lblEmployeePhoto.setIcon(new ImageIcon(image));
        }                   
    }//GEN-LAST:event_jButtonPhotoUploadActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButtonPhotoUpload;
    private javax.swing.JLabel jLabel_Photo;
    private com.toedter.calendar.JDateChooser jcalStartDate;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeeAge;
    private javax.swing.JLabel lblEmployeeEmail;
    private javax.swing.JLabel lblEmployeeGender;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblEmployeeLevel;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblEmployeePhnNumber;
    private javax.swing.JLabel lblEmployeePhoto;
    private javax.swing.JLabel lblEmployeePostitionTitle;
    private javax.swing.JLabel lblEmployeeStartDate;
    private javax.swing.JLabel lblEmployeeTeamInfo;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPT;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTI;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton r_btnFemale;
    private javax.swing.JRadioButton r_btnMale;
    private javax.swing.JTextField txtEmployeeAge;
    private javax.swing.JTextField txtEmployeeEmail;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtEmployeeLevel;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEmployeePhnNumber;
    private javax.swing.JTextField txtEmployeePositionTitle;
    private javax.swing.JTextField txtEmployeeTeamInfo;
    // End of variables declaration//GEN-END:variables


    

}
